---
name: module3_task2

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install required tools
        run: cd module3_task2 && sudo ./setup.sh

      - name: install markdownlint
        run: |
          cd module3_task2
          sudo gem install chef-utils -v 16.6.14
          sudo gem install mdl -v 0.11.0
      - name: lint
        run: sudo make lint -C module3_task2/

      - name: Unit test
        run: sudo make unit-tests -C module3_task2

      - name: test2
        run: sudo make integration-tests -C module3_task2

      - name: validate
        run: sudo make validate -C module3_task2

      - name: help
        run: sudo make help -C module3_task2

      - name: Build command
        run: sudo make build -C module3_task2

      - name: package
        run: sudo make package -C module3_task2
...
